# Generated by Django 3.2.6 on 2021-09-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticatedphoneaddress',
            name='authenticated_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='authenticatedphoneaddress',
            name='phone_mac_address',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
