# Generated by Django 3.2.6 on 2021-09-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210919_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='please format should be +233', max_length=15, unique=True),
        ),
    ]
