# Generated by Django 3.2.6 on 2021-08-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_agent_ucode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(default='FNET COMPANY @ GHANA', max_length=200),
            preserve_default=False,
        ),
    ]
