# Generated by Django 3.2.6 on 2021-10-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('Ashanti', 'Ashanti'), ('Greater Accra', 'Greater Accra'), ('Brong-Ahafo', 'Brong-Ahafo'), ('Northern', 'Northern'), ('Central', 'Central'), ('Upper East', 'Upper East'), ('Upper West', 'Upper West'), ('Eastern', 'Eastern'), ('Volta', 'Volta'), ('Western', 'Western')], max_length=50),
        ),
    ]
