# Generated by Django 3.2.6 on 2021-08-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agent_code',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
