# Generated by Django 3.2.6 on 2021-08-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_agent_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agent_code',
            field=models.IntegerField(unique=True),
        ),
    ]
