# Generated by Django 3.2.6 on 2021-08-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_agent_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agent_code',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
