# Generated by Django 3.2.6 on 2021-08-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210823_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='company_name',
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(default='FNET', max_length=200),
            preserve_default=False,
        ),
    ]
