# Generated by Django 3.2.6 on 2021-08-13 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMoneyWithDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('MTN', 'MTN'), ('VODAFONE', 'VODAFONE'), ('AIRTEL TIGO', 'AIRTEL TIGO')], max_length=11)),
                ('phone', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('id_type', models.CharField(choices=[('Passport', 'Passport'), ("Voter's Id", "Voter's Id"), ('Health Insurance', 'Health Insurance'), ('Driving License', 'Driving License'), ('Ghana National Card', 'Ghana National Card'), ('SSNIT Card', 'SSNIT Card')], max_length=100)),
                ('amount', models.FloatField()),
                ('date_withdrew', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MobileMoneyUsersRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('MTN', 'MTN'), ('VODAFONE', 'VODAFONE'), ('AIRTEL TIGO', 'AIRTEL TIGO')], max_length=11)),
                ('phone', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('id_type', models.CharField(choices=[('Passport', 'Passport'), ("Voter's Id", "Voter's Id"), ('Health Insurance', 'Health Insurance'), ('Driving License', 'Driving License'), ('Ghana National Card', 'Ghana National Card'), ('SSNIT Card', 'SSNIT Card')], max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='mobile_money_users')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MobileMoneyDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('MTN', 'MTN'), ('VODAFONE', 'VODAFONE'), ('AIRTEL TIGO', 'AIRTEL TIGO')], max_length=11)),
                ('phone', models.CharField(max_length=15)),
                ('other_phone', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('id_type', models.CharField(choices=[('Passport', 'Passport'), ("Voter's Id", "Voter's Id"), ('Health Insurance', 'Health Insurance'), ('Driving License', 'Driving License'), ('Ghana National Card', 'Ghana National Card'), ('SSNIT Card', 'SSNIT Card')], max_length=100)),
                ('amount', models.FloatField()),
                ('date_deposited', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
