# Generated by Django 3.2.6 on 2021-08-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilemoneyusersregistration',
            name='id_type',
            field=models.CharField(choices=[('Passport', 'Passport'), ("Voter's Id", "Voter's Id"), ('Health Insurance', 'Health Insurance'), ('Driving License', 'Driving License'), ('Ghana National Card', 'Ghana National Card'), ('SSNIT Card', 'SSNIT Card')], default='Ghana National Card', max_length=100),
        ),
        migrations.AlterField(
            model_name='mobilemoneyusersregistration',
            name='network',
            field=models.CharField(choices=[('MTN', 'MTN'), ('VODAFONE', 'VODAFONE'), ('AIRTEL TIGO', 'AIRTEL TIGO')], default='MTN', max_length=11),
        ),
    ]
