# Generated by Django 3.2.6 on 2021-08-28 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20210813_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilemoneyusersregistration',
            name='photo',
        ),
        migrations.CreateModel(
            name='MobileMoneyUserId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='mobile_money_users')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mobile_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mobilemoneyusersregistration')),
            ],
        ),
    ]
