# Generated by Django 3.2.6 on 2021-08-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210828_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilemoneyusersregistration',
            name='photo',
            field=models.ImageField(default='', upload_to='mobile_money_users'),
        ),
        migrations.DeleteModel(
            name='MobileMoneyUserId',
        ),
    ]
