# Generated by Django 3.2.6 on 2021-09-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210918_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencybankingdeposit',
            name='depositor_id_type',
            field=models.CharField(blank=True, choices=[('Passport', 'Passport'), ('Voters Id', 'Voters Id'), ('Health Insurance', 'Health Insurance'), ('Driving License', 'Driving License'), ('Ghana National Card', 'Ghana National Card'), ('SSNIT Card', 'SSNIT Card')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mobilemoneydeposit',
            name='depositor_id_type',
            field=models.CharField(blank=True, choices=[('Passport', 'Passport'), ('Voters Id', 'Voters Id'), ('Health Insurance', 'Health Insurance'), ('Driving License', 'Driving License'), ('Ghana National Card', 'Ghana National Card'), ('SSNIT Card', 'SSNIT Card')], default='', max_length=100),
        ),
    ]
