# Generated by Django 3.2.6 on 2021-08-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210829_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilemoneyusersregistration',
            name='photo',
        ),
    ]
