# Generated by Django 3.2.6 on 2021-08-30 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_remove_mobilemoneyusersregistration_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilemoneywithdraw',
            name='id_type',
        ),
        migrations.RemoveField(
            model_name='mobilemoneywithdraw',
            name='name',
        ),
        migrations.CreateModel(
            name='MomoPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('MTN', 'MTN'), ('VODAFONE', 'VODAFONE'), ('AIRTEL TIGO', 'AIRTEL TIGO')], max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('amount', models.IntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fraud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('reason', models.TextField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyBankingWithDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('Absa', 'Absa'), ('Access Bank', 'Access Bank'), ('ADB', 'ADB'), ('Bank of Africa', 'Bank of Africa'), ('Cal Bank', 'Cal Bank'), ('Consolidated Bank Ghana', 'Consolidated Bank Ghana'), ('Fidelity Bank', 'Fidelity Bank'), ('Ecobank', 'Ecobank'), ('First Atlantic Bank', 'First Atlantic Bank'), ('First Bank of Nigeria', 'First Bank of Nigeria'), ('GCB Bank Ltd', 'GCB Bank Ltd'), ('GHL Bank Ltd', 'GHL Bank Ltd'), ('GT Bank', 'GT Bank'), ('National Investment Bank', 'National Investment Bank'), ('Prudential Bank', 'Prudential Bank'), ('Republic Bank Limited', 'Republic Bank Limited'), ('Sahel Sahara Bank', 'Sahel Sahara Bank'), ('Societe General Ghana Ltd', 'Societe General Ghana Ltd'), ('Stanbic Bank', 'Stanbic Bank'), ('Standard Chartered Bank', 'Standard Chartered Bank'), ('United Bank Of Africa', 'United Bank Of Africa'), ('Universal Merchant Bank', 'Universal Merchant Bank'), ('Zenith bank', 'Zenith bank')], max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('amount', models.FloatField()),
                ('date_withdrew', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyBankingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('Absa', 'Absa'), ('Access Bank', 'Access Bank'), ('ADB', 'ADB'), ('Bank of Africa', 'Bank of Africa'), ('Cal Bank', 'Cal Bank'), ('Consolidated Bank Ghana', 'Consolidated Bank Ghana'), ('Fidelity Bank', 'Fidelity Bank'), ('Ecobank', 'Ecobank'), ('First Atlantic Bank', 'First Atlantic Bank'), ('First Bank of Nigeria', 'First Bank of Nigeria'), ('GCB Bank Ltd', 'GCB Bank Ltd'), ('GHL Bank Ltd', 'GHL Bank Ltd'), ('GT Bank', 'GT Bank'), ('National Investment Bank', 'National Investment Bank'), ('Prudential Bank', 'Prudential Bank'), ('Republic Bank Limited', 'Republic Bank Limited'), ('Sahel Sahara Bank', 'Sahel Sahara Bank'), ('Societe General Ghana Ltd', 'Societe General Ghana Ltd'), ('Stanbic Bank', 'Stanbic Bank'), ('Standard Chartered Bank', 'Standard Chartered Bank'), ('United Bank Of Africa', 'United Bank Of Africa'), ('Universal Merchant Bank', 'Universal Merchant Bank'), ('Zenith bank', 'Zenith bank')], default='GT Bank', max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('id_type', models.CharField(choices=[('Passport', 'Passport'), ("Voter's Id", "Voter's Id"), ('Health Insurance', 'Health Insurance'), ('Driving License', 'Driving License'), ('Ghana National Card', 'Ghana National Card'), ('SSNIT Card', 'SSNIT Card')], default='Ghana National Card', max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyBankingDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('Absa', 'Absa'), ('Access Bank', 'Access Bank'), ('ADB', 'ADB'), ('Bank of Africa', 'Bank of Africa'), ('Cal Bank', 'Cal Bank'), ('Consolidated Bank Ghana', 'Consolidated Bank Ghana'), ('Fidelity Bank', 'Fidelity Bank'), ('Ecobank', 'Ecobank'), ('First Atlantic Bank', 'First Atlantic Bank'), ('First Bank of Nigeria', 'First Bank of Nigeria'), ('GCB Bank Ltd', 'GCB Bank Ltd'), ('GHL Bank Ltd', 'GHL Bank Ltd'), ('GT Bank', 'GT Bank'), ('National Investment Bank', 'National Investment Bank'), ('Prudential Bank', 'Prudential Bank'), ('Republic Bank Limited', 'Republic Bank Limited'), ('Sahel Sahara Bank', 'Sahel Sahara Bank'), ('Societe General Ghana Ltd', 'Societe General Ghana Ltd'), ('Stanbic Bank', 'Stanbic Bank'), ('Standard Chartered Bank', 'Standard Chartered Bank'), ('United Bank Of Africa', 'United Bank Of Africa'), ('Universal Merchant Bank', 'Universal Merchant Bank'), ('Zenith bank', 'Zenith bank')], max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('other_phone', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('id_type', models.CharField(choices=[('Passport', 'Passport'), ("Voter's Id", "Voter's Id"), ('Health Insurance', 'Health Insurance'), ('Driving License', 'Driving License'), ('Ghana National Card', 'Ghana National Card'), ('SSNIT Card', 'SSNIT Card')], max_length=100)),
                ('amount', models.FloatField()),
                ('date_deposited', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
