# Generated by Django 3.2.6 on 2021-09-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210918_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencybankingdeposit',
            name='amount',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='agencybankingwithdraw',
            name='amount',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mobilemoneydeposit',
            name='amount',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mobilemoneywithdraw',
            name='amount',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='momopay',
            name='amount',
            field=models.CharField(max_length=500),
        ),
    ]
