# Generated by Django 3.2.6 on 2021-08-31 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210830_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraud',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='momopay',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
