# Generated by Django 3.2.6 on 2021-09-24 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20210919_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentsAccountsCompletedWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtn_physical', models.IntegerField()),
                ('mtn_eCash', models.IntegerField()),
                ('vodafone_physical', models.IntegerField()),
                ('vodafone_eCash', models.IntegerField()),
                ('airtel_tigo_physical', models.IntegerField()),
                ('airtel_tigo_eCash', models.IntegerField()),
                ('ecobank_physical', models.IntegerField()),
                ('ecobank_eCash', models.IntegerField()),
                ('calbank_physical', models.IntegerField()),
                ('calbank_eCash', models.IntegerField()),
                ('fidelity_physical', models.IntegerField()),
                ('fidelity_eCash', models.IntegerField()),
                ('date_closed', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentsAccountsStartedWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtn_physical', models.IntegerField()),
                ('mtn_eCash', models.IntegerField()),
                ('vodafone_physical', models.IntegerField()),
                ('vodafone_eCash', models.IntegerField()),
                ('airtel_tigo_physical', models.IntegerField()),
                ('airtel_tigo_eCash', models.IntegerField()),
                ('ecobank_physical', models.IntegerField()),
                ('ecobank_eCash', models.IntegerField()),
                ('calbank_physical', models.IntegerField()),
                ('calbank_eCash', models.IntegerField()),
                ('fidelity_physical', models.IntegerField()),
                ('fidelity_eCash', models.IntegerField()),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
