# Generated by Django 3.2.6 on 2021-08-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210831_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencybankingregistration',
            name='photo',
            field=models.ImageField(default='', upload_to='agency_abanking'),
        ),
        migrations.AddField(
            model_name='mobilemoneyusersregistration',
            name='photo',
            field=models.ImageField(default='', upload_to='mobile_money'),
        ),
    ]
