# Generated by Django 3.2.6 on 2021-09-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210831_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencybankingdeposit',
            name='account_number',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='agencybankingwithdraw',
            name='account_number',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
