# Generated by Django 3.2.6 on 2021-10-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210924_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentsaccountscompletedwith',
            old_name='airtel_tigo_physical',
            new_name='physical_cash',
        ),
        migrations.RenameField(
            model_name='agentsaccountsstartedwith',
            old_name='airtel_tigo_physical',
            new_name='physical_cash',
        ),
        migrations.RemoveField(
            model_name='agentsaccountscompletedwith',
            name='calbank_physical',
        ),
        migrations.RemoveField(
            model_name='agentsaccountscompletedwith',
            name='ecobank_physical',
        ),
        migrations.RemoveField(
            model_name='agentsaccountscompletedwith',
            name='fidelity_physical',
        ),
        migrations.RemoveField(
            model_name='agentsaccountscompletedwith',
            name='mtn_physical',
        ),
        migrations.RemoveField(
            model_name='agentsaccountscompletedwith',
            name='vodafone_physical',
        ),
        migrations.RemoveField(
            model_name='agentsaccountsstartedwith',
            name='calbank_physical',
        ),
        migrations.RemoveField(
            model_name='agentsaccountsstartedwith',
            name='ecobank_physical',
        ),
        migrations.RemoveField(
            model_name='agentsaccountsstartedwith',
            name='fidelity_physical',
        ),
        migrations.RemoveField(
            model_name='agentsaccountsstartedwith',
            name='mtn_physical',
        ),
        migrations.RemoveField(
            model_name='agentsaccountsstartedwith',
            name='vodafone_physical',
        ),
    ]
