# Generated by Django 3.2.6 on 2021-09-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210902_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencybankingdeposit',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='agencybankingwithdraw',
            name='account_number',
        ),
        migrations.AddField(
            model_name='agencybankingregistration',
            name='account_number',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
