# Generated by Django 3.2.6 on 2021-09-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210902_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agencybankingdeposit',
            old_name='other_phone',
            new_name='other_account',
        ),
    ]
