# Generated by Django 3.2.6 on 2021-09-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_agencybankingregistration_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencybankingregistration',
            name='id_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='mobilemoneyusersregistration',
            name='id_number',
            field=models.CharField(max_length=16),
        ),
    ]
