# Generated by Django 3.2.6 on 2021-09-05 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='agent2',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='agent1',
            new_name='sender',
        ),
    ]
