# Generated by Django 3.2.6 on 2021-09-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210906_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agencybankingdeposit',
            old_name='other_account',
            new_name='beneficiary_account_number',
        ),
        migrations.RenameField(
            model_name='agencybankingdeposit',
            old_name='id_type',
            new_name='depositor_id_type',
        ),
        migrations.RenameField(
            model_name='agencybankingdeposit',
            old_name='phone',
            new_name='depositor_number',
        ),
        migrations.RenameField(
            model_name='agencybankingwithdraw',
            old_name='phone',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='mobilemoneydeposit',
            old_name='other_phone',
            new_name='beneficiary_phone',
        ),
        migrations.RenameField(
            model_name='mobilemoneydeposit',
            old_name='id_type',
            new_name='depositor_id_type',
        ),
        migrations.RenameField(
            model_name='mobilemoneydeposit',
            old_name='phone',
            new_name='depositor_phone',
        ),
        migrations.RemoveField(
            model_name='agencybankingdeposit',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mobilemoneydeposit',
            name='name',
        ),
        migrations.AddField(
            model_name='agencybankingdeposit',
            name='beneficiary_name',
            field=models.CharField(default='Agent', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agencybankingdeposit',
            name='depositor_id_number',
            field=models.CharField(default='0000', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobilemoneydeposit',
            name='beneficiary_name',
            field=models.CharField(default='Agent', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobilemoneydeposit',
            name='depositor_number',
            field=models.CharField(default='0000', max_length=16),
            preserve_default=False,
        ),
    ]
