# Generated by Django 3.2.6 on 2021-09-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210907_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencybankingdeposit',
            name='depositor_id_type',
            field=models.CharField(choices=[('Passport', 'Passport'), ('Voters Id', 'Voters Id'), ('Health Insurance', 'Health Insurance'), ('Driving License', 'Driving License'), ('Ghana National Card', 'Ghana National Card'), ('SSNIT Card', 'SSNIT Card')], max_length=100),
        ),
        migrations.AlterField(
            model_name='agencybankingregistration',
            name='id_type',
            field=models.CharField(choices=[('Passport', 'Passport'), ('Voters Id', 'Voters Id'), ('Health Insurance', 'Health Insurance'), ('Driving License', 'Driving License'), ('Ghana National Card', 'Ghana National Card'), ('SSNIT Card', 'SSNIT Card')], default='Ghana National Card', max_length=100),
        ),
        migrations.AlterField(
            model_name='mobilemoneydeposit',
            name='depositor_id_type',
            field=models.CharField(choices=[('Passport', 'Passport'), ('Voters Id', 'Voters Id'), ('Health Insurance', 'Health Insurance'), ('Driving License', 'Driving License'), ('Ghana National Card', 'Ghana National Card'), ('SSNIT Card', 'SSNIT Card')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mobilemoneydeposit',
            name='network',
            field=models.CharField(choices=[('MTN', 'MTN'), ('VODAFONE', 'VODAFONE'), ('AIRTELTIGO', 'AIRTELTIGO')], max_length=11),
        ),
        migrations.AlterField(
            model_name='mobilemoneyusersregistration',
            name='id_type',
            field=models.CharField(choices=[('Passport', 'Passport'), ('Voters Id', 'Voters Id'), ('Health Insurance', 'Health Insurance'), ('Driving License', 'Driving License'), ('Ghana National Card', 'Ghana National Card'), ('SSNIT Card', 'SSNIT Card')], default='Ghana National Card', max_length=100),
        ),
        migrations.AlterField(
            model_name='mobilemoneyusersregistration',
            name='network',
            field=models.CharField(choices=[('MTN', 'MTN'), ('VODAFONE', 'VODAFONE'), ('AIRTELTIGO', 'AIRTELTIGO')], default='MTN', max_length=11),
        ),
        migrations.AlterField(
            model_name='mobilemoneywithdraw',
            name='network',
            field=models.CharField(choices=[('MTN', 'MTN'), ('VODAFONE', 'VODAFONE'), ('AIRTELTIGO', 'AIRTELTIGO')], max_length=11),
        ),
        migrations.AlterField(
            model_name='momopay',
            name='network',
            field=models.CharField(choices=[('MTN', 'MTN'), ('VODAFONE', 'VODAFONE'), ('AIRTELTIGO', 'AIRTELTIGO')], max_length=100),
        ),
    ]
